# Generated by Django 4.2.3 on 2025-01-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_id', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Course Details',
                'verbose_name_plural': 'Course Details',
            },
        ),
        migrations.CreateModel(
            name='ProgramDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Program Details',
                'verbose_name_plural': 'Program Details',
            },
        ),
    ]
