# Generated by Django 4.2.3 on 2024-01-31 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(blank=True, max_length=100, verbose_name='Branch Names')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(blank=True, max_length=100, verbose_name='College Names')),
                ('college_code', models.CharField(blank=True, max_length=100, verbose_name='College Code')),
            ],
            options={
                'verbose_name': 'Colleges',
                'verbose_name_plural': 'Colleges',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=100, verbose_name='Project Names')),
                ('project_description', models.CharField(blank=True, max_length=100, verbose_name='Project Descriptions')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_names', models.CharField(blank=True, max_length=100, verbose_name='Role Names')),
            ],
            options={
                'verbose_name': 'Roles',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_name', models.CharField(blank=True, max_length=100, verbose_name='Session Names')),
                ('batch', models.CharField(blank=True, max_length=100, verbose_name='Batches')),
                ('year', models.CharField(blank=True, max_length=100, verbose_name='Year')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tech_name', models.CharField(blank=True, max_length=100, verbose_name='Tech Names')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('college_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnsdc_users.colleges')),
                ('role_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnsdc_users.roles')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Roles',
                'verbose_name_plural': 'User Roles',
            },
        ),
        migrations.CreateModel(
            name='UserBranch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnsdc_users.branches')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_branch', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Branch',
                'verbose_name_plural': 'User Branches',
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nm_id', models.CharField(blank=True, max_length=100, verbose_name='nm_id')),
                ('anna_univ_id', models.CharField(blank=True, max_length=100, verbose_name='anna_univ_id')),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnsdc_users.branches')),
                ('college_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnsdc_users.colleges')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='std_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Details',
                'verbose_name_plural': 'Student Details',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, max_length=100, verbose_name='Group Names')),
                ('sessions_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnsdc_users.sessions')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='CourseMappings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnsdc_users.groups')),
                ('tech_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnsdc_users.technologies')),
            ],
            options={
                'verbose_name': 'Course Mappings',
                'verbose_name_plural': 'Course Mappings',
            },
        ),
        migrations.CreateModel(
            name='CollegeGroupSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projected_student_count', models.IntegerField(default=0)),
                ('team_size', models.IntegerField(default=0)),
                ('college_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnsdc_users.colleges')),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnsdc_users.groups')),
                ('sessions_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnsdc_users.sessions')),
            ],
            options={
                'verbose_name': 'College Group Session',
                'verbose_name_plural': 'College Group Sessions',
            },
        ),
        migrations.CreateModel(
            name='BranchTechnology',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnsdc_users.branches')),
                ('sessions_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnsdc_users.sessions')),
                ('tech_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnsdc_users.technologies')),
            ],
            options={
                'verbose_name': 'Branch Technology',
                'verbose_name_plural': 'Branch Technologies',
            },
        ),
    ]
