# Generated by Django 4.2.3 on 2023-07-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAidPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partners', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, choices=[('india', 'india'), ('us', 'us')], null=True)),
                ('partnerlink', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAidProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_slug', models.CharField(blank=True, max_length=100, null=True)),
                ('program_name', models.TextField(blank=True, max_length=100, null=True)),
                ('financialpartners_india', models.ManyToManyField(blank=True, related_name='programs_india', to='financial_aid.financialaidpartner')),
                ('financialpartners_us', models.ManyToManyField(blank=True, related_name='programs_us', to='financial_aid.financialaidpartner')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAidCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(blank=True, max_length=100, null=True)),
                ('course_name', models.TextField(blank=True, max_length=100, null=True)),
                ('financialpartners_india', models.ManyToManyField(blank=True, related_name='courses_india', to='financial_aid.financialaidpartner')),
                ('financialpartners_us', models.ManyToManyField(blank=True, related_name='courses_us', to='financial_aid.financialaidpartner')),
            ],
        ),
    ]
