# Generated by Django 4.2.3 on 2023-07-11 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibm_tnsdc', '0002_user_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibm_tnsdc.project'),
        ),
    ]
