# Generated by Django 4.2.3 on 2023-07-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibm_tnsdc', '0003_teammembers_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='project',
        ),
        migrations.AlterField(
            model_name='college',
            name='team_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='course_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
