# Generated by Django 4.2.3 on 2023-07-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibm_tnsdc', '0004_remove_teammembers_project_alter_college_team_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
