# Generated by Django 4.2.3 on 2023-07-30 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Colleges',
                'verbose_name_plural': 'Colleges',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('course_id', models.TextField(blank=True, null=True)),
                ('course_name', models.TextField(blank=True, null=True)),
                ('college', models.ManyToManyField(blank=True, related_name='all_colleges', to='ibm_tnsdc3.college')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, choices=[('Team Member', 'Team Member'), ('Team Mentor', 'Team Mentor')], max_length=30, null=True)),
                ('course_id', models.TextField(blank=True, null=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibm_tnsdc3.college')),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('team_size', models.IntegerField(blank=True, null=True)),
                ('members', models.ManyToManyField(limit_choices_to={'role': 'Team Member'}, related_name='teams', to='ibm_tnsdc3.user')),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'Team Mentor'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibm_tnsdc3.user')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibm_tnsdc3.project')),
            ],
            options={
                'verbose_name': 'Teams',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
