# Generated by Django 4.2.3 on 2023-08-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibm_tnsdc3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_size',
        ),
        migrations.AddField(
            model_name='college',
            name='team_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
