# Generated by Django 4.2.3 on 2023-08-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibm_tnsdc3', '0002_remove_team_team_size_college_team_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
