# Generated by Django 4.2.3 on 2023-08-10 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibm_tnsdc3', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'Team Member'}, related_name='teams', to='ibm_tnsdc3.user'),
        ),
        migrations.AlterField(
            model_name='team',
            name='mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Team Mentor'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibm_tnsdc3.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Team Member', 'Team Member'), ('Team Mentor', 'Team Mentor'), ('Spoc', 'Spoc'), ('Evaluator', 'Evaluator'), ('Principal', 'Principal')], max_length=30, null=True),
        ),
    ]
