# Generated by Django 4.2.3 on 2023-08-19 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibm_tnsdc3', '0004_alter_team_members_alter_team_mentor_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='course_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='evaluator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Team Mentor,Evaluator'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_evaluator', to='ibm_tnsdc3.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='evaluator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='nm_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'Team Member'}, related_name='teams_member', to='ibm_tnsdc3.user'),
        ),
        migrations.AlterField(
            model_name='team',
            name='mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Team Mentor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_mentor', to='ibm_tnsdc3.user'),
        ),
        migrations.CreateModel(
            name='TnsdcEnrollments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_enrolled', models.BooleanField(default=False)),
                ('is_registered', models.BooleanField(default=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='ibm_tnsdc3.user')),
            ],
        ),
    ]
