# Generated by Django 4.2.3 on 2023-08-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibm_tnsdc3', '0005_college_course_id_team_evaluator_user_evaluator_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TnsdcEnrollments',
            new_name='TnsdcEnrollment',
        ),
    ]
