# Generated by Django 4.2.3 on 2023-08-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibm_tnsdc3', '0006_rename_tnsdcenrollments_tnsdcenrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='evaluator',
            new_name='is_evaluator',
        ),
    ]
