# Generated by Django 4.2.3 on 2023-08-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibm_tnsdc3', '0007_rename_evaluator_user_is_evaluator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='evaluator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Evaluator'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_evaluator', to='ibm_tnsdc3.user'),
        ),
    ]
