# Generated by Django 4.2.3 on 2023-09-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibm_tnsdc3', '0012_alter_team_evaluator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tnsdcenrollment',
            options={'verbose_name': 'TnsdcEnrollments', 'verbose_name_plural': 'TnsdcEnrollments'},
        ),
        migrations.AddField(
            model_name='college',
            name='college_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'Team Member'}, related_name='teams_members', to='ibm_tnsdc3.user'),
        ),
        migrations.AlterField(
            model_name='team',
            name='mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Team Mentor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_mentors', to='ibm_tnsdc3.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Team Member', 'Team Member'), ('Team Mentor', 'Team Mentor'), ('Spoc', 'Spoc'), ('Evaluator', 'Evaluator'), ('Principal', 'Principal'), ('Admin', 'Admin')], max_length=30, null=True),
        ),
    ]
