# Generated by Django 4.2.3 on 2023-09-26 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibm_tnsdc3', '0013_alter_tnsdcenrollment_options_college_college_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TnsdcSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase1_submitted', models.BooleanField(default=False)),
                ('eval_a1', models.FloatField(default=0.0)),
                ('eval_a2', models.FloatField(default=0.0)),
                ('avg1', models.FloatField(default=0.0)),
                ('phase2_submitted', models.BooleanField(default=False)),
                ('eval_b1', models.FloatField(default=0.0)),
                ('eval_b2', models.FloatField(default=0.0)),
                ('avg2', models.FloatField(default=0.0)),
                ('phase3_submitted', models.BooleanField(default=False)),
                ('eval_c1', models.FloatField(default=0.0)),
                ('eval_c2', models.FloatField(default=0.0)),
                ('avg3', models.FloatField(default=0.0)),
                ('phase4_submitted', models.BooleanField(default=False)),
                ('eval_d1', models.FloatField(default=0.0)),
                ('eval_d2', models.FloatField(default=0.0)),
                ('avg4', models.FloatField(default=0.0)),
                ('phase5_submitted', models.BooleanField(default=False)),
                ('eval_e1', models.FloatField(default=0.0)),
                ('eval_e2', models.FloatField(default=0.0)),
                ('avg5', models.FloatField(default=0.0)),
                ('final_submission', models.BooleanField(default=False)),
                ('final_marks', models.FloatField(default=0.0)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibm_tnsdc3.college')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='ibm_tnsdc3.user')),
                ('team_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_team', to='ibm_tnsdc3.team')),
            ],
            options={
                'verbose_name': 'TnsdcSubmissions',
                'verbose_name_plural': 'TnsdcSubmissions',
            },
        ),
    ]
