# Generated by Django 4.2.3 on 2023-09-26 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibm_tnsdc3', '0014_tnsdcsubmission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tnsdcsubmission',
            unique_together={('email',)},
        ),
    ]
