# Generated by Django 4.2.3 on 2023-10-04 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibm_tnsdc3', '0015_alter_tnsdcsubmission_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnsdcsubmission',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='ibm_tnsdc3.user'),
        ),
    ]
