# Generated by Django 4.2.3 on 2023-12-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibm_tnsdc3', '0016_tnsdcsubmission_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.IntegerField(blank=True, choices=[('2023', '2023'), ('2024', '2024')], null=True),
        ),
    ]
