# Generated by Django 4.2.3 on 2024-01-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibm_tnsdc3', '0018_alter_user_batch_alter_user_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='technology',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Team Member', 'Team Member'), ('Team Mentor', 'Team Mentor'), ('Spoc', 'Spoc'), ('Evaluator', 'Evaluator'), ('Principal', 'Principal'), ('Admin', 'Admin')], max_length=30, null=True),
        ),
    ]
