# Generated by Django 4.2.3 on 2024-01-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibm_tnsdc3', '0019_user_branch_user_technology_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Team Member', 'Team Member'), ('Team Mentor', 'Team Mentor'), ('Spoc', 'Spoc'), ('Evaluator', 'Evaluator'), ('Principal', 'Principal'), ('Admin', 'Admin')], max_length=30, null=True),
        ),
    ]
