# Generated by Django 4.2.3 on 2025-03-21 08:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'ContentType',
                'verbose_name_plural': 'ContentType',
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Class',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='ncert_sko.studentclass')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='PdfLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(blank=True, max_length=500, null=True)),
                ('action_url', models.URLField(blank=True, max_length=500, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='ncert_sko.contenttype')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='ncert_sko.subject')),
            ],
            options={
                'verbose_name': 'PDFLinks',
                'verbose_name_plural': 'PDFLinks',
            },
        ),
        migrations.CreateModel(
            name='PdfDownloadTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('downloaded', models.BooleanField(default=False)),
                ('pdf_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='ncert_sko.pdflinks')),
            ],
            options={
                'verbose_name': 'PDFDownload Tracker',
                'verbose_name_plural': 'PDFDownload Tracker',
            },
        ),
    ]
