# Generated by Django 4.2.3 on 2025-03-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncert_sko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdflinks',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
