# Generated by Django 4.2.3 on 2025-03-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncert_sko', '0002_pdflinks_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdflinks',
            name='file',
        ),
        migrations.AddField(
            model_name='studentclass',
            name='class_value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pdflinks',
            name='action_url',
            field=models.FileField(blank=True, null=True, upload_to='pdf/ncert/'),
        ),
    ]
