# Generated by Django 4.2.3 on 2025-03-23 17:31

from django.db import migrations, models
import ncert_sko.models


class Migration(migrations.Migration):

    dependencies = [
        ('ncert_sko', '0003_remove_pdflinks_file_studentclass_class_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdflinks',
            name='action_url',
            field=models.FileField(blank=True, null=True, upload_to=ncert_sko.models.upload_to_dynamic_path),
        ),
    ]
